// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: envelope.proto

package grpctransport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterEnvelope is the gRPC wire format for inter-node messages.
// The payload field carries a gob-encoded actor message; all routing
// metadata is in native proto fields so gateways, proxies, and
// observability tools can inspect/route without decoding the payload.
type ClusterEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Routing headers — arbitrary key/value pairs for gateway routing,
	// tracing propagation, traffic shaping, etc.
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Sender identification.
	SenderNode    string `protobuf:"bytes,2,opt,name=sender_node,json=senderNode,proto3" json:"sender_node,omitempty"`
	SenderActorId string `protobuf:"bytes,3,opt,name=sender_actor_id,json=senderActorId,proto3" json:"sender_actor_id,omitempty"`
	// Target identification.
	TargetNode    string `protobuf:"bytes,4,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	TargetActorId string `protobuf:"bytes,5,opt,name=target_actor_id,json=targetActorId,proto3" json:"target_actor_id,omitempty"`
	// PID generation tracking.
	Namespace  string `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Generation uint64 `protobuf:"varint,7,opt,name=generation,proto3" json:"generation,omitempty"`
	// Message metadata.
	TypeName      string `protobuf:"bytes,8,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	SchemaVersion string `protobuf:"bytes,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	MessageId     uint64 `protobuf:"varint,10,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Gob-encoded actor message payload.
	Payload []byte `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	// Ask/reply support.
	IsAsk        bool            `protobuf:"varint,12,opt,name=is_ask,json=isAsk,proto3" json:"is_ask,omitempty"`
	AskRequestId string          `protobuf:"bytes,13,opt,name=ask_request_id,json=askRequestId,proto3" json:"ask_request_id,omitempty"`
	AskReplyTo   *RemotePIDProto `protobuf:"bytes,14,opt,name=ask_reply_to,json=askReplyTo,proto3" json:"ask_reply_to,omitempty"` // nil when not an ask
	// Timing.
	SentAtUnixNano int64 `protobuf:"varint,15,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterEnvelope) Reset() {
	*x = ClusterEnvelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterEnvelope) ProtoMessage() {}

func (x *ClusterEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterEnvelope.ProtoReflect.Descriptor instead.
func (*ClusterEnvelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterEnvelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ClusterEnvelope) GetSenderNode() string {
	if x != nil {
		return x.SenderNode
	}
	return ""
}

func (x *ClusterEnvelope) GetSenderActorId() string {
	if x != nil {
		return x.SenderActorId
	}
	return ""
}

func (x *ClusterEnvelope) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *ClusterEnvelope) GetTargetActorId() string {
	if x != nil {
		return x.TargetActorId
	}
	return ""
}

func (x *ClusterEnvelope) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ClusterEnvelope) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ClusterEnvelope) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ClusterEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ClusterEnvelope) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ClusterEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClusterEnvelope) GetIsAsk() bool {
	if x != nil {
		return x.IsAsk
	}
	return false
}

func (x *ClusterEnvelope) GetAskRequestId() string {
	if x != nil {
		return x.AskRequestId
	}
	return ""
}

func (x *ClusterEnvelope) GetAskReplyTo() *RemotePIDProto {
	if x != nil {
		return x.AskReplyTo
	}
	return nil
}

func (x *ClusterEnvelope) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

// RemotePIDProto is the wire representation of a remote actor PID.
type RemotePIDProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePIDProto) Reset() {
	*x = RemotePIDProto{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePIDProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePIDProto) ProtoMessage() {}

func (x *RemotePIDProto) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePIDProto.ProtoReflect.Descriptor instead.
func (*RemotePIDProto) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *RemotePIDProto) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *RemotePIDProto) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RemotePIDProto) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RemotePIDProto) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\rgrpctransport\"\x8a\x05\n" +
	"\x0fClusterEnvelope\x12E\n" +
	"\aheaders\x18\x01 \x03(\v2+.grpctransport.ClusterEnvelope.HeadersEntryR\aheaders\x12\x1f\n" +
	"\vsender_node\x18\x02 \x01(\tR\n" +
	"senderNode\x12&\n" +
	"\x0fsender_actor_id\x18\x03 \x01(\tR\rsenderActorId\x12\x1f\n" +
	"\vtarget_node\x18\x04 \x01(\tR\n" +
	"targetNode\x12&\n" +
	"\x0ftarget_actor_id\x18\x05 \x01(\tR\rtargetActorId\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"generation\x18\a \x01(\x04R\n" +
	"generation\x12\x1b\n" +
	"\ttype_name\x18\b \x01(\tR\btypeName\x12%\n" +
	"\x0eschema_version\x18\t \x01(\tR\rschemaVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\n" +
	" \x01(\x04R\tmessageId\x12\x18\n" +
	"\apayload\x18\v \x01(\fR\apayload\x12\x15\n" +
	"\x06is_ask\x18\f \x01(\bR\x05isAsk\x12$\n" +
	"\x0eask_request_id\x18\r \x01(\tR\faskRequestId\x12?\n" +
	"\fask_reply_to\x18\x0e \x01(\v2\x1d.grpctransport.RemotePIDProtoR\n" +
	"askReplyTo\x12)\n" +
	"\x11sent_at_unix_nano\x18\x0f \x01(\x03R\x0esentAtUnixNano\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x0eRemotePIDProto\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generation2`\n" +
	"\x10ClusterTransport\x12L\n" +
	"\x06Stream\x12\x1e.grpctransport.ClusterEnvelope\x1a\x1e.grpctransport.ClusterEnvelope(\x010\x01BBZ@github.com/tripleclabs/westcoast/src/actor/cluster/grpctransportb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_envelope_proto_goTypes = []any{
	(*ClusterEnvelope)(nil), // 0: grpctransport.ClusterEnvelope
	(*RemotePIDProto)(nil),  // 1: grpctransport.RemotePIDProto
	nil,                     // 2: grpctransport.ClusterEnvelope.HeadersEntry
}
var file_envelope_proto_depIdxs = []int32{
	2, // 0: grpctransport.ClusterEnvelope.headers:type_name -> grpctransport.ClusterEnvelope.HeadersEntry
	1, // 1: grpctransport.ClusterEnvelope.ask_reply_to:type_name -> grpctransport.RemotePIDProto
	0, // 2: grpctransport.ClusterTransport.Stream:input_type -> grpctransport.ClusterEnvelope
	0, // 3: grpctransport.ClusterTransport.Stream:output_type -> grpctransport.ClusterEnvelope
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
