// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: envelope.proto

package grpctransport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterTransport_Stream_FullMethodName = "/grpctransport.ClusterTransport/Stream"
)

// ClusterTransportClient is the client API for ClusterTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterTransport is the gRPC service for inter-node communication.
// Authentication is handled via gRPC metadata (HMAC-based shared secret)
// and/or mTLS at the transport layer — not a separate RPC.
type ClusterTransportClient interface {
	// Stream opens a bidirectional envelope stream between two nodes.
	// The caller's identity is established from metadata and the first
	// envelope's sender_node field.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClusterEnvelope, ClusterEnvelope], error)
}

type clusterTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterTransportClient(cc grpc.ClientConnInterface) ClusterTransportClient {
	return &clusterTransportClient{cc}
}

func (c *clusterTransportClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClusterEnvelope, ClusterEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterTransport_ServiceDesc.Streams[0], ClusterTransport_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClusterEnvelope, ClusterEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTransport_StreamClient = grpc.BidiStreamingClient[ClusterEnvelope, ClusterEnvelope]

// ClusterTransportServer is the server API for ClusterTransport service.
// All implementations must embed UnimplementedClusterTransportServer
// for forward compatibility.
//
// ClusterTransport is the gRPC service for inter-node communication.
// Authentication is handled via gRPC metadata (HMAC-based shared secret)
// and/or mTLS at the transport layer — not a separate RPC.
type ClusterTransportServer interface {
	// Stream opens a bidirectional envelope stream between two nodes.
	// The caller's identity is established from metadata and the first
	// envelope's sender_node field.
	Stream(grpc.BidiStreamingServer[ClusterEnvelope, ClusterEnvelope]) error
	mustEmbedUnimplementedClusterTransportServer()
}

// UnimplementedClusterTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterTransportServer struct{}

func (UnimplementedClusterTransportServer) Stream(grpc.BidiStreamingServer[ClusterEnvelope, ClusterEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedClusterTransportServer) mustEmbedUnimplementedClusterTransportServer() {}
func (UnimplementedClusterTransportServer) testEmbeddedByValue()                          {}

// UnsafeClusterTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterTransportServer will
// result in compilation errors.
type UnsafeClusterTransportServer interface {
	mustEmbedUnimplementedClusterTransportServer()
}

func RegisterClusterTransportServer(s grpc.ServiceRegistrar, srv ClusterTransportServer) {
	// If the following call panics, it indicates UnimplementedClusterTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterTransport_ServiceDesc, srv)
}

func _ClusterTransport_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterTransportServer).Stream(&grpc.GenericServerStream[ClusterEnvelope, ClusterEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTransport_StreamServer = grpc.BidiStreamingServer[ClusterEnvelope, ClusterEnvelope]

// ClusterTransport_ServiceDesc is the grpc.ServiceDesc for ClusterTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpctransport.ClusterTransport",
	HandlerType: (*ClusterTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ClusterTransport_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "envelope.proto",
}
